apiVersion: v1
kind: Pod
metadata: 
  name: pod-config-demo
  labels:
    project: roboshop
  annotations:
    jenkins.url: "https://jenkins.joindevops.com/build/5"
  
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100mi"
        memory: "64M"
      limits:
        cpu: "250mi"
        memory: "128M"
    envFrom:
    - configMapRef:
        name: pod-config