apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: headless
    project: roboshop

spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: headless

  template:
    metadata:
      labels:
        purpose: headless
 
    spec:
      containers:
      - name: nginx
        image: nginx:trixie-perl
---
apiVersion: v1
kind: Service
metadata:
  name: service-lb
spec:
  type: LoadBalancer
  selector:
      purpose: headless

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007