apiVersion: v1
kind: Service
metadata:
  name: service-lb
spec:
  type: {{ .Values.deployment.servicetype}}
  selector:
      purpose: helm-demo

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007