apiVersion: v1
kind: Service
metadata:
  name: mongodb

spec:
  selector:
      component: mongodb
      project: roboshop
      tier: db
  ports:
    - protocol: TCP
      port: 27017 #service port
      targetPort: 27017 #container port